#! /bin/sh

# Geometry
bspc config border_width	1
bspc config window_gap		15
bspc config top_padding		25

if [ $(monitorconnected DP1-1) ]; then
  bspc config -m DP1-1 top padding 0
fi

# Colors

# Defaults
bspc config split_ratio 		        0.5
bspc config borderless_monocle 		  true
bspc config gapless_monocle		      true
bspc config focus_by_distance		    true
bspc config history_aware_focus		  true
bspc config focus_follows_pointer	  true
bspc config pointer_follows_monitor	true
bspc config auto_cancel			        true

# Create default desktops I-IX
if [ $(monitorconnected DP1-1) ]; then
  bspc monitor eDP1  -d I II III IV V VI VII
  bspc monitor DP1-1 -d VIII IX X

  bspc desktop IX -l monocle
  bspc desktop X -l monocle

  bspc rule -a Firefox desktop=X
  bspc rule -a Thunderbird desktop=X
  bspc rule -a Inkscape desktop=IX
  bspc rule -a Gimp desktop=IX
else
  bspc monitor I II III IV V VI VII VIII IX X

  bspc desktop I -l monocle 
  bspc desktop X -l monocle 

  bspc rule -a Firefox desktop=I
  bspc rule -a Thunderbird desktop=I
  bspc rule -a Inkscape desktop=X
  bspc rule -a Gimp desktop=X

fi

bspc rule -a feh state=floating
